### ISSUE TITLE
Math (linear algebra) optimization library (Eigen)

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1069]
From: https://issues.numenta.org/browse/NPC-320

For darwin86/64 ( https://github.com/numenta/nupic/pull/181 ) we use vDSP/vecLib for optimized math functions. 
There is no such support for linux (and other platforms), an alternative is Eigen ( http://eigen.tuxfamily.org/index.php?title=Main_Page )

I'd like to suggest: 
1. evaluate speed comparison for our usecase for Eigen/vDSP. 
2. based on the results, use eigen on linux\* (and in future win,arm) platform, or for all platforms exclusively. 
3. find more places in codebase where our code can be replaced by these libs.  

Using Eigen would have the following advantages: 
- multiplatform (Linux, Mac, Win, ARM, ...32/64bit)
- "multi-compiler" (gcc,clang,msvc,..)
- less code (if switched to eigen only) 

In any case, I'd vote for using these lib(s) as much as possible- reduced the "hard" code we have to write,  testing/optimizations done on "their" side.

**Comment by rcrowder** [comment]
(If required) Looks like Eigen can be tested here; http://docs.biicode.com/c++/examples/eigen.html
