### ISSUE TITLE
PositiveExperimentTests.test_MultiStep fails

### ISSUE THREAD

**Issue by jefffohl** [numenta/nupic-legacy#893]
Error encountered using nupic as of commit b7f531ddf25f053d1a66ac6e9544142d4723dbb1

PositiveExperimentTests.test_MultiStep is failing on my machine. I am wondering if perhaps this has to do with the use of Python 2.7.6 (most others seem to be using 2.7.5). This is just a guess, but since this failure does not seem to be happening to others, I suspect it is due to an environment dependency of some sort. Note that I do have MySQL installed and running, and this command executes successfully:

`python $NUPIC/examples/swarm/test_db.py`

I am not sure where to start debugging this, so if anyone has any clues, they would be much appreciated!

Pastebin: http://pastebin.com/eVbP3P2F

**Comment by RDaneelOlivav** [comment]
Hi,
Got this error too, how did you salve it at the end?

**Comment by rhyolight** [comment]
@RDaneelOlivav Can you paste the exact error you saw? Was it this?

```
E         TypeError: fileConfig() got an unexpected keyword argument 'disable_existing_loggers'
```

Thanks.

**Comment by RDaneelOlivav** [comment]
Hi,
I got the error pasted in the .rst added in this email.
I also get this error:

python $NUPIC/examples/swarm/test_db.py

This script will validate that your MySQL is setup correctly for NuPIC.
MySQL is required for NuPIC swarming. The settings are defined in
NuPIC's configuration files in $NUPIC/nupic/support/nupic-default.xml
Out of the box those settings contain MySQL's default access
credentials.

Retrieved the following settings from NuPIC configuration:
    host   :     localhost
    port   :     3306
    user   :     root
    passwd :     Kodama0

Traceback (most recent call last):
  File
"/home/rdaneel/Kodama/kodama_project/external_gits/nupic/examples/swarm/test_db.py",
line 48, in <module>
    raise RuntimeError("Couldn't connect to the database."
RuntimeError: Couldn't connect to the database. Please ensure you have MySQL
 installed, running, and accessible using the NuPIC configuration settings.

But I've reinstalled MySQL 3 times and assuerd that it had no Password to
access by root.

Do you have any idea what it might be happening?
the other tests work perfectly.


2015-03-10 17:27 GMT+01:00 Matthew Taylor <notifications@github.com>:

**Comment by rhyolight** [comment]
@RDaneelOlivav Even though MySQL is installed, it doesn't look like it is running. You'll need to figure out how to start the mysql server on your OS.
